from tkinter import *
app=Tk()
app.title("Login page")
app.geometry("500x500")
# bg=PhotoImage(file="1.jpg")
# frame1=Frame(app)
# frame1.pack(pady=20)
lb1=Label(app,text="user id")
lb1.grid(pady=20,row=0,column=0)
en1=Entry(app)
en1.grid(pady=20,row=0,column=1)
lb2=Label(app,text="Password")
lb2.grid(pady=20,row=1,column=0)
en2=Entry(app,show='*')
en2.grid(pady=20,row=1,column=1)
btn=Button(app,text="Login")
btn.grid(pady=20,row=2,column=1)
app.mainloop()